-- MySQL Script generated by MySQL Workbench
-- 07/04/19 23:38:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_syspedidos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_syspedidos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_syspedidos` DEFAULT CHARACTER SET utf8 ;
USE `bd_syspedidos` ;

-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_empleado` (
  `tb_empleado_id` INT NOT NULL AUTO_INCREMENT,
  `cod_cargo` VARCHAR(6) NULL COMMENT 'catalogo: 001',
  `cod_area` VARCHAR(6) NULL COMMENT 'catalogo: 002',
  `cod_zona` VARCHAR(6) NULL COMMENT 'catalogo: 003',
  `fec_ini_vigencia` DATE NULL,
  `fec_fin_vigencia` DATE NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_empleado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_catalogo` (
  `param_catalogo` VARCHAR(3) NOT NULL,
  `param_catalogo_elemento` VARCHAR(3) NOT NULL,
  `descripcion_corta` VARCHAR(200) NULL,
  `descricpcion` TEXT NULL,
  `tipo` CHAR(1) NULL COMMENT 'C: Cabecera\nD: Detalle',
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`param_catalogo`, `param_catalogo_elemento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_cliente` (
  `tb_cliente_id` INT NOT NULL AUTO_INCREMENT,
  `num_ruc` VARCHAR(11) NULL,
  `razon_social` VARCHAR(400) NULL,
  `cod_zona` VARCHAR(6) NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_cliente_id`),
  UNIQUE INDEX `razon_social_UNIQUE` (`razon_social` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_persona_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_persona_contacto` (
  `tb_persona_contacto_id` INT NOT NULL AUTO_INCREMENT,
  `tb_cliente_id` INT NOT NULL,
  `seleccion_defecto` INT NULL DEFAULT 1 COMMENT '0:No es seleccionada por defecto\n1: Seleccionada por defecto (Para atender pedido, recepcionar pedido, firmar recepción, etc)',
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_persona_contacto_id`),
  INDEX `fk_tb_persona_contacto_tb_cliente1_idx` (`tb_cliente_id` ASC),
  CONSTRAINT `fk_tb_persona_contacto_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id`)
    REFERENCES `bd_syspedidos`.`tb_cliente` (`tb_cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_datos_personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_datos_personales` (
  `tb_datos_personales_id` INT NOT NULL AUTO_INCREMENT,
  `tb_persona_contacto_id` INT NULL,
  `tb_empleado_id` INT NULL,
  `cod_tipo_documento` VARCHAR(6) NULL COMMENT 'catalogo: 004',
  `num_documento` VARCHAR(45) NULL,
  `nombres` VARCHAR(100) NULL,
  `apellido_paterno` VARCHAR(50) NULL,
  `apellido_materno` VARCHAR(50) NULL,
  `email` VARCHAR(150) NULL,
  `fec_nacimiento` DATE NULL,
  `celular` VARCHAR(45) NULL,
  `telefono1` VARCHAR(45) NULL,
  `telefono2` VARCHAR(45) NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_datos_personales_id`),
  INDEX `fk_tb_datos_personales_tb_persona_contacto_idx` (`tb_persona_contacto_id` ASC),
  INDEX `fk_tb_datos_personales_tb_empleado1_idx` (`tb_empleado_id` ASC),
  CONSTRAINT `fk_tb_datos_personales_tb_persona_contacto`
    FOREIGN KEY (`tb_persona_contacto_id`)
    REFERENCES `bd_syspedidos`.`tb_persona_contacto` (`tb_persona_contacto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_datos_personales_tb_empleado1`
    FOREIGN KEY (`tb_empleado_id`)
    REFERENCES `bd_syspedidos`.`tb_empleado` (`tb_empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_categoria_producto` (
  `tb_categoria_producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NULL,
  `tb_categoria_producto_id_padre` INT NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_categoria_producto_id`),
  INDEX `fk_tb_categoria_producto_tb_categoria_producto1_idx` (`tb_categoria_producto_id_padre` ASC),
  CONSTRAINT `fk_tb_categoria_producto_tb_categoria_producto1`
    FOREIGN KEY (`tb_categoria_producto_id_padre`)
    REFERENCES `bd_syspedidos`.`tb_categoria_producto` (`tb_categoria_producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_producto` (
  `tb_producto_id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(100) NULL,
  `cod_marca` VARCHAR(6) NULL COMMENT 'cod_categoria',
  `tb_categoria_producto_id` INT NOT NULL,
  `cod_modelo` VARCHAR(6) NULL,
  `numero_serie` VARCHAR(100) NULL,
  `descripcion` VARCHAR(200) NULL,
  `stock` MEDIUMTEXT NULL,
  `lote` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `precio_venta` FLOAT NULL,
  `precio_compra` FLOAT NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` VARCHAR(45) NULL,
  PRIMARY KEY (`tb_producto_id`),
  INDEX `fk_tb_producto_tb_categoria_producto1_idx` (`tb_categoria_producto_id` ASC),
  UNIQUE INDEX `numero_serie_UNIQUE` (`numero_serie` ASC),
  CONSTRAINT `fk_tb_producto_tb_categoria_producto1`
    FOREIGN KEY (`tb_categoria_producto_id`)
    REFERENCES `bd_syspedidos`.`tb_categoria_producto` (`tb_categoria_producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_ubigeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_ubigeo` (
  `tb_ubigeo_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(80) NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_ubigeo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_direccion` (
  `tb_direccion_id` INT NOT NULL AUTO_INCREMENT,
  `tb_ubigeo_id` INT NOT NULL,
  `tb_cliente_id` INT NULL,
  `tb_datos_personales_id` INT NULL,
  `urbanizacion` VARCHAR(80) NULL,
  `avenida` VARCHAR(80) NULL,
  `jiron` VARCHAR(80) NULL,
  `calle` VARCHAR(80) NULL,
  `manzana` VARCHAR(5) NULL,
  `lote` VARCHAR(5) NULL,
  `numero` VARCHAR(10) NULL,
  `letra` VARCHAR(2) NULL,
  `piso` INT NULL,
  `bloque` VARCHAR(80) NULL,
  `predeterminado` INT NULL DEFAULT 1 COMMENT '1:Predeterminado\n2: No predeterminado\nUn cliente puede terner más de una dirección, por lo que debe haber un predeterminado.\nUn empleado debería tener al menos registrada una dirección',
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_direccion_id`),
  INDEX `fk_tb_direccion_tb_ubigeo1_idx` (`tb_ubigeo_id` ASC),
  INDEX `fk_tb_direccion_tb_cliente1_idx` (`tb_cliente_id` ASC),
  INDEX `fk_tb_direccion_tb_datos_personales1_idx` (`tb_datos_personales_id` ASC),
  CONSTRAINT `fk_tb_direccion_tb_ubigeo1`
    FOREIGN KEY (`tb_ubigeo_id`)
    REFERENCES `bd_syspedidos`.`tb_ubigeo` (`tb_ubigeo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_direccion_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id`)
    REFERENCES `bd_syspedidos`.`tb_cliente` (`tb_cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_direccion_tb_datos_personales1`
    FOREIGN KEY (`tb_datos_personales_id`)
    REFERENCES `bd_syspedidos`.`tb_datos_personales` (`tb_datos_personales_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_pedido` (
  `tb_pedido_id` INT NOT NULL AUTO_INCREMENT,
  `cod_estado_pedido` VARCHAR(6) NULL,
  `tb_cliente_id` INT NOT NULL,
  `tb_direccion_id` INT NOT NULL,
  `fecha_tentativa_entrega` DATE NULL,
  `fecha_entrega` DATETIME NULL,
  `monto_base` VARCHAR(45) NULL COMMENT 'Monto total bruto del pedido',
  `monto_final` DOUBLE NULL COMMENT 'Monto total neto, luego de aplicar algún descuento en caso se dé.',
  `usu_entrega` VARCHAR(45) NULL,
  `origen_registro` INT NOT NULL COMMENT '1: APP MOVIL\n2: APP WEB\n3: BATCH',
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_pedido_id`),
  INDEX `fk_tb_pedido_tb_cliente1_idx` (`tb_cliente_id` ASC),
  INDEX `fk_tb_pedido_tb_direccion1_idx` (`tb_direccion_id` ASC),
  CONSTRAINT `fk_tb_pedido_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id`)
    REFERENCES `bd_syspedidos`.`tb_cliente` (`tb_cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_direccion1`
    FOREIGN KEY (`tb_direccion_id`)
    REFERENCES `bd_syspedidos`.`tb_direccion` (`tb_direccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_pedido_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_pedido_detalle` (
  `tb_pedido_detalle_id` INT NOT NULL AUTO_INCREMENT,
  `tb_pedido_id` INT NOT NULL,
  `tb_producto_id` INT NOT NULL,
  `precio_unidad_final` FLOAT NULL,
  `cantidad` FLOAT NULL,
  `observacion` TEXT NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_pedido_detalle_id`),
  INDEX `fk_tb_pedido_detalle_tb_pedido1_idx` (`tb_pedido_id` ASC),
  INDEX `fk_tb_pedido_detalle_tb_producto1_idx` (`tb_producto_id` ASC),
  CONSTRAINT `fk_tb_pedido_detalle_tb_pedido1`
    FOREIGN KEY (`tb_pedido_id`)
    REFERENCES `bd_syspedidos`.`tb_pedido` (`tb_pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_detalle_tb_producto1`
    FOREIGN KEY (`tb_producto_id`)
    REFERENCES `bd_syspedidos`.`tb_producto` (`tb_producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_usuario` (
  `tb_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `en_sesion` INT NULL DEFAULT 0 COMMENT '1: Está en sesion\n0: No está en sesión',
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  `tb_empleado_id` INT NOT NULL,
  PRIMARY KEY (`tb_usuario_id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_tb_usuario_tb_empleado1_idx` (`tb_empleado_id` ASC),
  CONSTRAINT `fk_tb_usuario_tb_empleado1`
    FOREIGN KEY (`tb_empleado_id`)
    REFERENCES `bd_syspedidos`.`tb_empleado` (`tb_empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_rol` (
  `tb_rol_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_rol_usuario` (
  `tb_rol_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `tb_rol_id` INT NOT NULL,
  `tb_usuario_id` INT NOT NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_rol_usuario_id`),
  INDEX `fk_tb_rol_usuario_tb_rol1_idx` (`tb_rol_id` ASC),
  INDEX `fk_tb_rol_usuario_tb_usuario1_idx` (`tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_rol_usuario_tb_rol1`
    FOREIGN KEY (`tb_rol_id`)
    REFERENCES `bd_syspedidos`.`tb_rol` (`tb_rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_rol_usuario_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `bd_syspedidos`.`tb_usuario` (`tb_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_menu` (
  `tb_menu_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `icono` VARCHAR(50) NULL,
  `visible_web` INT NULL DEFAULT 1 COMMENT '1: Visible en web\n0: No visible en web',
  `visible_movil` INT NULL DEFAULT 0 COMMENT '1: Visible en móvil\n0: No visible en móvil',
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_syspedidos`.`tb_rol_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_syspedidos`.`tb_rol_menu` (
  `tb_rol_menu_id` INT NOT NULL AUTO_INCREMENT,
  `tb_rol_id` INT NOT NULL,
  `tb_menu_id` INT NOT NULL,
  `activo` INT NULL DEFAULT 1,
  `usu_reg` VARCHAR(45) NULL,
  `fec_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_modif` VARCHAR(45) NULL,
  `fec_modif` DATETIME NULL,
  PRIMARY KEY (`tb_rol_menu_id`),
  INDEX `fk_tb_rol_menu_tb_rol1_idx` (`tb_rol_id` ASC),
  INDEX `fk_tb_rol_menu_tb_menu1_idx` (`tb_menu_id` ASC),
  CONSTRAINT `fk_tb_rol_menu_tb_rol1`
    FOREIGN KEY (`tb_rol_id`)
    REFERENCES `bd_syspedidos`.`tb_rol` (`tb_rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_rol_menu_tb_menu1`
    FOREIGN KEY (`tb_menu_id`)
    REFERENCES `bd_syspedidos`.`tb_menu` (`tb_menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
